package vavi.awt.image.jna.avif;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : avif/avif.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class avifFraction extends Structure {
	public int n;
	public int d;
	public avifFraction() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("n", "d");
	}
	public avifFraction(int n, int d) {
		super();
		this.n = n;
		this.d = d;
	}
	public avifFraction(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends avifFraction implements Structure.ByReference {
	}
	public static class ByValue extends avifFraction implements Structure.ByValue {
	}
}
