package vavi.awt.image.jna.avif;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : avif/avif.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class avifPixelAspectRatioBox extends Structure {
	public int hSpacing;
	public int vSpacing;
	public avifPixelAspectRatioBox() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("hSpacing", "vSpacing");
	}
	public avifPixelAspectRatioBox(int hSpacing, int vSpacing) {
		super();
		this.hSpacing = hSpacing;
		this.vSpacing = vSpacing;
	}
	public avifPixelAspectRatioBox(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends avifPixelAspectRatioBox implements Structure.ByReference {
		
	}

    public static class ByValue extends avifPixelAspectRatioBox implements Structure.ByValue {
		
	}
}
