package vavi.awt.image.jna.avif;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : avif/avif.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class avifContentLightLevelInformationBox extends Structure {
	public short maxCLL;
	public short maxPALL;
	public avifContentLightLevelInformationBox() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("maxCLL", "maxPALL");
	}
	public avifContentLightLevelInformationBox(short maxCLL, short maxPALL) {
		super();
		this.maxCLL = maxCLL;
		this.maxPALL = maxPALL;
	}
	public avifContentLightLevelInformationBox(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends avifContentLightLevelInformationBox implements Structure.ByReference {
	}
	public static class ByValue extends avifContentLightLevelInformationBox implements Structure.ByValue {
	}
}
