package vavi.awt.image.jna.avif;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Collections;
import java.util.List;
/**
 * <i>native declaration : avif/avif.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class avifImageRotation extends Structure {
	/** legal values: [0-3] */
	public byte angle;
	public avifImageRotation() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Collections.singletonList("angle");
	}
	/** @param angle legal values: [0-3] */
	public avifImageRotation(byte angle) {
		super();
		this.angle = angle;
	}
	public avifImageRotation(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends avifImageRotation implements Structure.ByReference {
	}

    public static class ByValue extends avifImageRotation implements Structure.ByValue {
	}
}
