package vavi.awt.image.jna.avif;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : avif/avif.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class avifCodecConfigurationBox extends Structure {
	/** unsigned int (3) seq_profile; */
	public byte seqProfile;
	/** unsigned int (5) seq_level_idx_0; */
	public byte seqLevelIdx0;
	/** unsigned int (1) seq_tier_0; */
	public byte seqTier0;
	/** unsigned int (1) high_bitdepth; */
	public byte highBitdepth;
	/** unsigned int (1) twelve_bit; */
	public byte twelveBit;
	/** unsigned int (1) monochrome; */
	public byte monochrome;
	/** unsigned int (1) chroma_subsampling_x; */
	public byte chromaSubsamplingX;
	/** unsigned int (1) chroma_subsampling_y; */
	public byte chromaSubsamplingY;
	/** unsigned int (2) chroma_sample_position; */
	public byte chromaSamplePosition;
	public avifCodecConfigurationBox() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("seqProfile", "seqLevelIdx0", "seqTier0", "highBitdepth", "twelveBit", "monochrome", "chromaSubsamplingX", "chromaSubsamplingY", "chromaSamplePosition");
	}
	/**
	 * @param seqProfile unsigned int (3) seq_profile;<br>
	 * @param seqLevelIdx0 unsigned int (5) seq_level_idx_0;<br>
	 * @param seqTier0 unsigned int (1) seq_tier_0;<br>
	 * @param highBitdepth unsigned int (1) high_bitdepth;<br>
	 * @param twelveBit unsigned int (1) twelve_bit;<br>
	 * @param monochrome unsigned int (1) monochrome;<br>
	 * @param chromaSubsamplingX unsigned int (1) chroma_subsampling_x;<br>
	 * @param chromaSubsamplingY unsigned int (1) chroma_subsampling_y;<br>
	 * @param chromaSamplePosition unsigned int (2) chroma_sample_position;
	 */
	public avifCodecConfigurationBox(byte seqProfile, byte seqLevelIdx0, byte seqTier0, byte highBitdepth, byte twelveBit, byte monochrome, byte chromaSubsamplingX, byte chromaSubsamplingY, byte chromaSamplePosition) {
		super();
		this.seqProfile = seqProfile;
		this.seqLevelIdx0 = seqLevelIdx0;
		this.seqTier0 = seqTier0;
		this.highBitdepth = highBitdepth;
		this.twelveBit = twelveBit;
		this.monochrome = monochrome;
		this.chromaSubsamplingX = chromaSubsamplingX;
		this.chromaSubsamplingY = chromaSubsamplingY;
		this.chromaSamplePosition = chromaSamplePosition;
	}
	public avifCodecConfigurationBox(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends avifCodecConfigurationBox implements Structure.ByReference {
		
	};
	public static class ByValue extends avifCodecConfigurationBox implements Structure.ByValue {
		
	};
}
